### PR TITLE
SRE-1233 added pidMode

### PR DESCRIPTION
**Pull request by rafaebury**

### CODE REVIEW

**Comment by AlvaroRacero** [comment]
Do you think it makes sense to update our fork with the community module? It is already covered by them.

https://github.com/cloudposse/terraform-aws-ecs-container-definition/blob/master/variables.tf#L269

**Comment by rafaebury** [comment]
> Do you think it makes sense to update our fork with the community module? It is already covered by them.
> 
> https://github.com/cloudposse/terraform-aws-ecs-container-definition/blob/master/variables.tf#L269

On the one hand, I tried the version including the `privileged` key but a higher terraform version is requested. 
On the other hand, the community module doesn't support the `pidMode` key :cry:

**Comment by ebury-sergiorobles** [comment]
> On the one hand, I tried the version including the `privileged` key but a higher terraform version is requested.

The 0.12/master tag  seems compatible with our terraform version and have the privileged variable. 

Have you tested this one 0.12/master tag ?  🤔

**Comment by rafaebury** [comment]
> > On the one hand, I tried the version including the `privileged` key but a higher terraform version is requested.
> 
> The 0.12/master tag seems compatible with our terraform version and have the privileged variable.
> 
> Have you tested this one 0.12/master tag ? thinking

I got confused. I tried the last version of the official module (0.58.1) and it required a higher terraform version than 0.12.31.
Just to clarify, In this PR I am not including the privileged flag, it was already included in version 0.16.0.
I am just including the pidMode flag that it is not supported by the official module.

**Review by AlvaroRacero — APPROVED** [review]

**Review by ebury-sergiorobles — APPROVED** [review]

**Pull request merged**
